# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_one.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(539, 493)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.P1PushButtonTest = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P1PushButtonTest.sizePolicy().hasHeightForWidth())
        self.P1PushButtonTest.setSizePolicy(sizePolicy)
        self.P1PushButtonTest.setObjectName(_fromUtf8("P1PushButtonTest"))
        self.gridLayout_2.addWidget(self.P1PushButtonTest, 0, 1, 1, 1)
        self.P1PushButtonSave = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P1PushButtonSave.sizePolicy().hasHeightForWidth())
        self.P1PushButtonSave.setSizePolicy(sizePolicy)
        self.P1PushButtonSave.setObjectName(_fromUtf8("P1PushButtonSave"))
        self.gridLayout_2.addWidget(self.P1PushButtonSave, 0, 0, 1, 1)
        self.P1PushButtonNext = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P1PushButtonNext.sizePolicy().hasHeightForWidth())
        self.P1PushButtonNext.setSizePolicy(sizePolicy)
        self.P1PushButtonNext.setObjectName(_fromUtf8("P1PushButtonNext"))
        self.gridLayout_2.addWidget(self.P1PushButtonNext, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.P1LabelDatabase = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P1LabelDatabase.sizePolicy().hasHeightForWidth())
        self.P1LabelDatabase.setSizePolicy(sizePolicy)
        self.P1LabelDatabase.setMinimumSize(QtCore.QSize(0, 0))
        self.P1LabelDatabase.setObjectName(_fromUtf8("P1LabelDatabase"))
        self.gridLayout_3.addWidget(self.P1LabelDatabase, 1, 0, 1, 1)
        self.P1LabelUser = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P1LabelUser.sizePolicy().hasHeightForWidth())
        self.P1LabelUser.setSizePolicy(sizePolicy)
        self.P1LabelUser.setObjectName(_fromUtf8("P1LabelUser"))
        self.gridLayout_3.addWidget(self.P1LabelUser, 2, 0, 1, 1)
        self.P1LabelPassword = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P1LabelPassword.sizePolicy().hasHeightForWidth())
        self.P1LabelPassword.setSizePolicy(sizePolicy)
        self.P1LabelPassword.setObjectName(_fromUtf8("P1LabelPassword"))
        self.gridLayout_3.addWidget(self.P1LabelPassword, 3, 0, 1, 1)
        self.P1LineEditUser = QtGui.QLineEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P1LineEditUser.sizePolicy().hasHeightForWidth())
        self.P1LineEditUser.setSizePolicy(sizePolicy)
        self.P1LineEditUser.setObjectName(_fromUtf8("P1LineEditUser"))
        self.gridLayout_3.addWidget(self.P1LineEditUser, 2, 1, 1, 1)
        self.P1LineEditDatabase = QtGui.QLineEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P1LineEditDatabase.sizePolicy().hasHeightForWidth())
        self.P1LineEditDatabase.setSizePolicy(sizePolicy)
        self.P1LineEditDatabase.setObjectName(_fromUtf8("P1LineEditDatabase"))
        self.gridLayout_3.addWidget(self.P1LineEditDatabase, 1, 1, 1, 1)
        self.P1LineEditPassword = QtGui.QLineEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P1LineEditPassword.sizePolicy().hasHeightForWidth())
        self.P1LineEditPassword.setSizePolicy(sizePolicy)
        self.P1LineEditPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.P1LineEditPassword.setObjectName(_fromUtf8("P1LineEditPassword"))
        self.gridLayout_3.addWidget(self.P1LineEditPassword, 3, 1, 1, 1)
        self.P1LabelHost = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P1LabelHost.sizePolicy().hasHeightForWidth())
        self.P1LabelHost.setSizePolicy(sizePolicy)
        self.P1LabelHost.setObjectName(_fromUtf8("P1LabelHost"))
        self.gridLayout_3.addWidget(self.P1LabelHost, 0, 0, 1, 1)
        self.P1LineEditHost = QtGui.QLineEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P1LineEditHost.sizePolicy().hasHeightForWidth())
        self.P1LineEditHost.setSizePolicy(sizePolicy)
        self.P1LineEditHost.setObjectName(_fromUtf8("P1LineEditHost"))
        self.gridLayout_3.addWidget(self.P1LineEditHost, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.P1LabelTitle = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P1LabelTitle.sizePolicy().hasHeightForWidth())
        self.P1LabelTitle.setSizePolicy(sizePolicy)
        self.P1LabelTitle.setMinimumSize(QtCore.QSize(0, 50))
        self.P1LabelTitle.setObjectName(_fromUtf8("P1LabelTitle"))
        self.verticalLayout.addWidget(self.P1LabelTitle)
        self.P1LabelConnect = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P1LabelConnect.sizePolicy().hasHeightForWidth())
        self.P1LabelConnect.setSizePolicy(sizePolicy)
        self.P1LabelConnect.setMinimumSize(QtCore.QSize(0, 40))
        self.P1LabelConnect.setObjectName(_fromUtf8("P1LabelConnect"))
        self.verticalLayout.addWidget(self.P1LabelConnect)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.P1LineEditHost, self.P1LineEditDatabase)
        Dialog.setTabOrder(self.P1LineEditDatabase, self.P1LineEditUser)
        Dialog.setTabOrder(self.P1LineEditUser, self.P1LineEditPassword)
        Dialog.setTabOrder(self.P1LineEditPassword, self.P1PushButtonTest)
        Dialog.setTabOrder(self.P1PushButtonTest, self.P1PushButtonSave)
        Dialog.setTabOrder(self.P1PushButtonSave, self.P1PushButtonNext)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.P1PushButtonTest.setText(_translate("Dialog", "Test", None))
        self.P1PushButtonSave.setText(_translate("Dialog", "Save", None))
        self.P1PushButtonNext.setText(_translate("Dialog", "Next", None))
        self.P1LabelDatabase.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Database</p></body></html>", None))
        self.P1LabelUser.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">User</p></body></html>", None))
        self.P1LabelPassword.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Password</p></body></html>", None))
        self.P1LabelHost.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Host</p></body></html>", None))
        self.P1LabelTitle.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Database Driven App</span></p></body></html>", None))
        self.P1LabelConnect.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Connect to Database</p></body></html>", None))

